### ISSUE TITLE
Third-party and dependencies refactoring (for version 4.0.1)

### ISSUE THREAD

**Issue by theopolis** [osquery/osquery#5652]
This is a *parent issue* tracking the smaller bodies of work needed.

High level goals:

1. Provide contributors autonomy to update third-party dependencies (with a PR). This means no requirement to upload artifacts to private/controlled hosting like S3.
2. Protect the build and management of third-party dependencies from unintentional influences from system state. The builder will be provided flexible options for using and discovering third-party dependencies.
3. Pin, or enforce, certain required third-party dependency expectations.

There are secondary goals such as reproducible builds, offline builds, system-toolchain compatibility, etc. Making progress towards these goals is in scope for this refactor.

While this is being worked on by multiple developers we will use the branch [`thirdparty-submodules`](https://github.com/osquery/osquery/tree/thirdparty-submodules). 

- [x] #5639 Use a single build system for dependencies
- [x] #5611 Support building osquery with `-fPIE`
- [x] #5609 Recommend or provide a portable toolchain for building on Linux
- [ ] #5598 Support offline builds, meaning the build-generator should not use the network
- [x] #5591 Update to the latest boost within source
- [x] Update pre-built dependencies (or their from-source options) to use newer libraries where available
