### ISSUE TITLE
Upgrade Python tools to Python3 before Python2 EOL

### ISSUE THREAD

**Issue by mike-myers-tob** [osquery/osquery#5762]
# Task

To address the [January 1st 2020 EOL for Python 2](https://pythonclock.org), update any use of Python2 in osquery's build and test systems to Python3, and eliminate Python2 as a build prerequisite.

- [x] The Python shebang lines should be `#!/usr/bin/env python3` [unless the code is compatible with both Python 2.x and 3.x](https://www.python.org/dev/peps/pep-0394/#for-python-script-publishers). If our script [says it requires Python2 but the shebang line just says `python`](https://github.com/osquery/osquery/blob/6481b34e2382ffb5b4c469de3157c63e0ed23ea3/tools/formatting/git-clang-format.py), it will fail if the system resolves that to Python 3.

Python in the osquery build and test systems:
- [x] `osquery/tools/analysis/*`
- [x] `osquery/tools/build_defs/oss/osquery/*`
- [x] `osquery/tools/codegen/*`
- [x] `osquery/tools/deployment/*`
- [x] `osquery/tools/get_platform.py`
- [x] `osquery/tools/hooks/pre_commit.py`
- [x] `osquery/tools/tests/*`
- [x] `osquery/tools/cmake/downloader.py`
- [x] `osquery/tools/formatting/*`

**Comment by adhaamehab** [comment]
Hi, Can I start working on this?

**Comment by theopolis** [comment]
Sure thing! I'm not aware of any ongoing work related to upgrading.

**Comment by Smjert** [comment]
I'd like to reopen this, since while the script has been updated, CMake it's still calling the format and format_check scripts with Python 2.
Doing a quick change to use Python 3 and testing format_check, I see the following error:

```
d /home/smjert/Development/osquery/src && /usr/local/bin/cmake -E env PATH=/usr/local/osquery-toolchain/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games /usr/bin/python3.6 /home/smjert/Development/osquery/src/tools/formatting/format-check.py --exclude-folders libraries/cmake/source origin/master
Traceback (most recent call last):
  File "/home/smjert/Development/osquery/src/tools/formatting/format-check.py", line 90, in <module>
    sys.exit(not main())
  File "/home/smjert/Development/osquery/src/tools/formatting/format-check.py", line 87, in main
    return check(base_commit, args.exclude_folders) if base_commit is not None else False
  File "/home/smjert/Development/osquery/src/tools/formatting/format-check.py", line 40, in check
    elif out.startswith("no modified files to format"):
TypeError: startswith first arg must be bytes or a tuple of bytes, not str
```
