### ISSUE TITLE
New release checklist for version 4.1.1

### ISSUE THREAD

**Issue by theopolis** [osquery/osquery#5985]
# New release checklist

## Before creating a GitHub tag

- [x] Review the milestone issues, move unfinished to the next release, close the milestone.
- [x] Update the `CHANGELOG.md`, review and merge the change.
- [x] Assure testable packages are available for the `#core` channel on Slack.
- [x] Ask for a volunteer to make a GitHub tag.
- [x] Assure the ChangeLog shows up in the tag release notes.

## After creating a GitHub tag

- [x] Create packages and upload to S3 (for download use only).
- [x] Update the website with the new release and schema.
- [ ] Publish the website changes.
- [ ] Publish the new packages into the hosted repos.
- [ ] Advertise the new release. :)

**Comment by theopolis** [comment]
> Assure the ChangeLog shows up in the tag release notes.

This was not the case and it looks like it never has been. We have been copy-pasting the changelog markdown into the GitHub releases notes.

**Comment by theopolis** [comment]
Tracking TODOs here: https://github.com/osquery/osquery/milestone/45

**Comment by directionless** [comment]
> This was not the case and it looks like it never has been. We have been copy-pasting the changelog markdown into the GitHub releases notes.

AFAIK, that's correct.
