### ISSUE TITLE
New release checklist for version 4.1.2

### ISSUE THREAD

**Issue by theopolis** [osquery/osquery#6133]
## Before creating a GitHub tag

- [x] Review the milestone issues, move unfinished to the next release, close the milestone.
- [x] Update the `CHANGELOG.md`, review and merge the change.
- [x] Assure testable packages are available for the `#core` channel on Slack.
- [x] Ask for a volunteer to make a GitHub tag.
- [x] Assure the ChangeLog shows up in the tag release notes.

## After creating a GitHub tag

- [x] Create packages and upload to S3 (for download use only).
- [x] Update the website with the new release and schema.
- [x] Publish the website changes.
- [x] Publish the new packages into the hosted repos.
- [x] Advertise the new release. :)

**Comment by theopolis** [comment]
Website PR: https://github.com/osquery/osquery-site/pull/159
