### ISSUE TITLE
New release checklist for version 4.5.0

### ISSUE THREAD

**Issue by theopolis** [osquery/osquery#6640]
## Specific follow up for 4.5.0

- [x] Move the remaining issues in the 4.5.0 milestone to 4.6.0
- [x] Confirm if https://github.com/osquery/osquery/issues/6626 is release blocking
- [x] Review status of https://github.com/osquery/osquery/pull/6607 and check if release blocking
- [x] Review open and active pull requests
- [x] Create a draft [blog post for the website talking about ARM64 availability](https://github.com/osquery/osquery-site/pull/183) (Teddy creates draft, Alessandro will review and post)
- [x] Create a "heads up" notice on the downloads page for the ARM64 blog post

## Before creating a GitHub tag

- [x] Review the milestone issues, move unfinished to the next release, close the milestone.
- [x] Update the `CHANGELOG.md`, review and merge the change.
- [x] Assure testable packages are available for the `#core` channel on Slack.
- [x] Ask for a volunteer to make a GitHub tag.
- [x] Assure the ChangeLog shows up in the tag release notes.

## After creating a GitHub tag

- [x] Create packages and upload to S3 (for download use only).
- [x] Update the website with the new release and schema.
- [x] Publish the website changes.
- [ ] Publish the new packages into the hosted repos.
- [ ] Bump or ping the [Homebrew Cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/osquery.rb).
- [ ] Advertise the new release. :)

**Comment by theopolis** [comment]
Website release: https://github.com/osquery/osquery-site/pull/184

**Comment by theopolis** [comment]
Heads up @peterlewis, for the Homebrew Cask update. :D

**Comment by peterlewis** [comment]
Sure thing! PR [submitted](https://github.com/Homebrew/homebrew-cask/pull/89550)!

**Comment by nabilschear** [comment]
any update on when 4.5 packages will be published to the hosted repos?

**Comment by theopolis** [comment]
We are moving forward with 4.5.1 due to some bugs found in 4.5.0.
