### ISSUE TITLE
New release checklist for version 5.0.0

### ISSUE THREAD

**Issue by mike-myers-tob** [osquery/osquery#7218]
# New release checklist

## Before creating a GitHub tag

- [ ] Review the milestone issues, move unfinished to the next release, close the milestone.
- [ ] Update the `CHANGELOG.md`, review and merge the change.
- [ ] Assure testable packages are available for the `#core` channel on Slack.
- [ ] Ask for a volunteer to make a GitHub tag.
- [ ] Assure the ChangeLog shows up in the tag release notes.

## After creating a GitHub tag

- [ ] Create packages and upload to S3 (for download use only).
- [ ] Update the website with the new release and schema.
- [ ] Publish the website changes.
- [ ] Publish the new packages into the hosted repos.
- [ ] Bump or ping the [Homebrew Cask](https://github.com/Homebrew/homebrew-cask/blob/master/Casks/osquery.rb). Note: change the `facebook` strings there too.
- [ ] Advertise the new release. :)
