### ISSUE TITLE
Formalize a Packaging Checklist and Add Test Automation

### ISSUE THREAD

**Issue by sharvilshah** [osquery/osquery#7290]
A lot has changed recently wrt packaging, CI, codesigning, identifiers, paths, etc

I thought this would be a good place to catch all of this as a sort of checklist (feel free to close if this belongs in the wiki or somewhere else, but following is a quick brain dump, I will edit and spruce it up as i go along)

Perhaps we can also try and automate this slowly, maybe as a scheduled github workflow.

Briefly: 

### macOS

- [x] check codesign on pkg (spctl, codesign)
- [x] check paths: pkg, app bundle, launchd
- [x] check osqueryctl and the path it refers
- [x] check entitlement and profile
- [x] check launchd correctly starts/stops service

### Linux

- [x] check paths
- [x] check systemd service installs correctly

### Windows

(I will like some help on this)

**Comment by mike-myers-tob** [comment]
Related: https://github.com/osquery/osquery/issues/5795

**Comment by mike-myers-tob** [comment]
What's left to do on this issue? Automating the Windows code-signing, or something else? We've been kicking it forward for a year, maybe it should be closed in favor of a new issue specific to the remaining goal.

**Comment by directionless** [comment]
This clearly isn't happening.
